# Este es nuetro primer archivo de config para realizar un deploy con Kubernetes,
# utilizamos Minikube para levantar un cluster de prueba local y activando luego containers
# basados en la imagen de prueba que subimos recientemente en nuestra cuenta de hub.docker.com

# El archivo se organiza en 2 secciones:

# Sección 1: deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: coder53120-deploy
spec:
  # Cantidad de instancias (containers) para nuestro cluster
  replicas: 3
  selector:
    matchLabels:
      app: coder53120
  template:
    metadata:
      labels:
        app: coder53120
    spec:
      containers:
      - name: coder53120
        # imagen de origen a utilizar para los containers
        image: mundostr/artillery_class_36:1.0.0
        ports:
        - containerPort: 5000
        # Podemos configurar las variables de entorno necesarias
        env:
        - name: MONGODB_URI
          value: "mongodb+srv://coder_53120:coder2024@clustercoder.sxqjiud.mongodb.net/coder_53120"
        # Always siempre trata de descargar la última versión disponible de la imagen cada vez que
        # se deben lanzar un container, excepto que tenga en cache local una con el mismo digest
        # Ver tags vs digest (https://kubernetes.io/docs/concepts/containers/images/)
        imagePullPolicy: Always

# Sección 2: servicio
# Este es el servicio a través del cual podremos utilizar los recursos del cluster
---
apiVersion: v1
kind: Service
metadata:
  name: coder53120-service
spec:
  selector:
    app: coder53120
  ports:
  - protocol: TCP
    port: 5000
    targetPort: 5000
  type: LoadBalancer
